// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnlzoltcklkjpdaijxcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubHpvbHRja2xranBkYWlqeGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mjk4NDIsImV4cCI6MjA2OTAwNTg0Mn0.CcKEoUJTWz-ebqMfKgvZmfTQs-8NRnl1YP8dfsc2gSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});