// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndpciowgmznncbjunsrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcGNpb3dnbXpubmNianVuc3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODM4NzYsImV4cCI6MjA4ODU1OTg3Nn0.HLtXzcsI5yCNLAmUyteBBtLbe97OEsb39Wj5BLiPp6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});